# -*- coding: utf-8 -*-
# **********************************************************************
#
# Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************
#
# Ice version 3.6.3
#
# <auto-generated>
#
# Generated from file `PetFood.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module PetFoodSensors
_M_PetFoodSensors = Ice.openModule('PetFoodSensors')
__name__ = 'PetFoodSensors'

if 'SensorControl' not in _M_PetFoodSensors.__dict__:
    _M_PetFoodSensors.SensorControl = Ice.createTempClass()
    class SensorControl(Ice.Object):
        def __init__(self):
            if Ice.getType(self) == _M_PetFoodSensors.SensorControl:
                raise RuntimeError('PetFoodSensors.SensorControl is an abstract class')

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::PetFoodSensors::SensorControl')

        def ice_id(self, current=None):
            return '::PetFoodSensors::SensorControl'

        def ice_staticId():
            return '::PetFoodSensors::SensorControl'
        ice_staticId = staticmethod(ice_staticId)

        def motorTime(self, time, current=None):
            pass

        def givefood(self, weight, current=None):
            pass

        def getContainerFood(self, current=None):
            pass

        def getFoodEated(self, current=None):
            pass

        def eatingNow(self, current=None):
            pass

        def getWeight(self, current=None):
            pass

        def __str__(self):
            return IcePy.stringify(self, _M_PetFoodSensors._t_SensorControl)

        __repr__ = __str__

    _M_PetFoodSensors.SensorControlPrx = Ice.createTempClass()
    class SensorControlPrx(Ice.ObjectPrx):

        def motorTime(self, time, _ctx=None):
            return _M_PetFoodSensors.SensorControl._op_motorTime.invoke(self, ((time, ), _ctx))

        def begin_motorTime(self, time, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_PetFoodSensors.SensorControl._op_motorTime.begin(self, ((time, ), _response, _ex, _sent, _ctx))

        def end_motorTime(self, _r):
            return _M_PetFoodSensors.SensorControl._op_motorTime.end(self, _r)

        def givefood(self, weight, _ctx=None):
            return _M_PetFoodSensors.SensorControl._op_givefood.invoke(self, ((weight, ), _ctx))

        def begin_givefood(self, weight, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_PetFoodSensors.SensorControl._op_givefood.begin(self, ((weight, ), _response, _ex, _sent, _ctx))

        def end_givefood(self, _r):
            return _M_PetFoodSensors.SensorControl._op_givefood.end(self, _r)

        def getContainerFood(self, _ctx=None):
            return _M_PetFoodSensors.SensorControl._op_getContainerFood.invoke(self, ((), _ctx))

        def begin_getContainerFood(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_PetFoodSensors.SensorControl._op_getContainerFood.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_getContainerFood(self, _r):
            return _M_PetFoodSensors.SensorControl._op_getContainerFood.end(self, _r)

        def getFoodEated(self, _ctx=None):
            return _M_PetFoodSensors.SensorControl._op_getFoodEated.invoke(self, ((), _ctx))

        def begin_getFoodEated(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_PetFoodSensors.SensorControl._op_getFoodEated.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_getFoodEated(self, _r):
            return _M_PetFoodSensors.SensorControl._op_getFoodEated.end(self, _r)

        def eatingNow(self, _ctx=None):
            return _M_PetFoodSensors.SensorControl._op_eatingNow.invoke(self, ((), _ctx))

        def begin_eatingNow(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_PetFoodSensors.SensorControl._op_eatingNow.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_eatingNow(self, _r):
            return _M_PetFoodSensors.SensorControl._op_eatingNow.end(self, _r)

        def getWeight(self, _ctx=None):
            return _M_PetFoodSensors.SensorControl._op_getWeight.invoke(self, ((), _ctx))

        def begin_getWeight(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_PetFoodSensors.SensorControl._op_getWeight.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_getWeight(self, _r):
            return _M_PetFoodSensors.SensorControl._op_getWeight.end(self, _r)

        def checkedCast(proxy, facetOrCtx=None, _ctx=None):
            return _M_PetFoodSensors.SensorControlPrx.ice_checkedCast(proxy, '::PetFoodSensors::SensorControl', facetOrCtx, _ctx)
        checkedCast = staticmethod(checkedCast)

        def uncheckedCast(proxy, facet=None):
            return _M_PetFoodSensors.SensorControlPrx.ice_uncheckedCast(proxy, facet)
        uncheckedCast = staticmethod(uncheckedCast)

        def ice_staticId():
            return '::PetFoodSensors::SensorControl'
        ice_staticId = staticmethod(ice_staticId)

    _M_PetFoodSensors._t_SensorControlPrx = IcePy.defineProxy('::PetFoodSensors::SensorControl', SensorControlPrx)

    _M_PetFoodSensors._t_SensorControl = IcePy.defineClass('::PetFoodSensors::SensorControl', SensorControl, -1, (), True, False, None, (), ())
    SensorControl._ice_type = _M_PetFoodSensors._t_SensorControl

    SensorControl._op_motorTime = IcePy.Operation('motorTime', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), None, ())
    SensorControl._op_givefood = IcePy.Operation('givefood', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_int, False, 0),), (), None, ())
    SensorControl._op_getContainerFood = IcePy.Operation('getContainerFood', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), IcePy._t_int, False, 0), ())
    SensorControl._op_getFoodEated = IcePy.Operation('getFoodEated', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), IcePy._t_int, False, 0), ())
    SensorControl._op_eatingNow = IcePy.Operation('eatingNow', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), IcePy._t_bool, False, 0), ())
    SensorControl._op_getWeight = IcePy.Operation('getWeight', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), IcePy._t_int, False, 0), ())

    _M_PetFoodSensors.SensorControl = SensorControl
    del SensorControl

    _M_PetFoodSensors.SensorControlPrx = SensorControlPrx
    del SensorControlPrx

# End of module PetFoodSensors
